language: node_js
sudo: false
node_js:
  - "4.2"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
services:
  - mysql
  - redis
env:
  - TRAVIS=travis CXX=g++-4.8